CREATE TABLE `mh_admin_log` (
  `log_idx` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '로그번호',
  `log_gidx` char(20) DEFAULT NULL COMMENT '로그그룹번호(동작 작성된 로그는 같은 그룹번호를 가짐)',
  `log_level` tinyint(4) DEFAULT '0' COMMENT '0:none,1:error,2:debug,3:info',
  `log_svr_ip` varchar(15) DEFAULT NULL COMMENT '서버아이피',
  `log_domain` varchar(64) DEFAULT NULL COMMENT '도메인',
  `log_url` varchar(250) DEFAULT NULL COMMENT '호출URL(REQUEST_URI)',
  `log_qstr` varchar(200) DEFAULT NULL COMMENT 'QUERY_STRING',
  `log_referer` varchar(200) DEFAULT NULL COMMENT '리퍼럴',
  `log_title` varchar(50) DEFAULT NULL COMMENT '로그타이틀',
  `log_msg` varchar(200) DEFAULT NULL COMMENT '로그메세지',
  `log_result` varchar(50) DEFAULT NULL COMMENT '로그결과',
  `log_val1` varchar(50) DEFAULT NULL COMMENT '검색용값1',
  `log_val2` varchar(50) DEFAULT NULL COMMENT '검색용값2',
  `log_num1` float DEFAULT NULL COMMENT '검색용번호1',
  `log_num2` float DEFAULT NULL COMMENT '검색용번호2',
  `log_etc` mediumtext COMMENT '그외입력값',
  `log_insert_date` datetime DEFAULT NULL COMMENT '로그작성일',
  `log_ip` varchar(15) DEFAULT NULL COMMENT '요청IP',
  PRIMARY KEY (`log_idx`),
  KEY `IDX_TITLE` (`log_title`),
  KEY `IDX_VAL1` (`log_val1`),
  KEY `IDX_NUM1` (`log_num1`),
  KEY `IDX_NUM2` (`log_num2`),
  KEY `IDX_VAL2` (`log_val2`),
  KEY `LOG_DATE` (`log_insert_date`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='관리자 로그용'
