ALTER TABLE `mh_log`
	ADD COLUMN `log_method` ENUM('CLI','ERR','GET','POST','HEAD','PUT','DELETE','CONNECT','OPTIONS','TRACE','PATCH') DEFAULT 'ERR' NULL COMMENT '호출메소드(REQUEST_METHOD)' AFTER `log_domain`;

ALTER TABLE `mh_admin_log`
	ADD COLUMN `log_method` ENUM('CLI','ERR','GET','POST','HEAD','PUT','DELETE','CONNECT','OPTIONS','TRACE','PATCH') DEFAULT 'ERR' NULL COMMENT '호출메소드(REQUEST_METHOD)' AFTER `log_domain`;
